### ISSUE TITLE
Any news on a standalone version without ValhallaMMO?

### ISSUE THREAD

**Issue by FaultyFunctions** [Athlaeos/ValhallaTrinkets#1]
Hello! I'd love to use ValhallaTrinkets but don't want to go full MMO on our server. I was wondering if there was any news on a fully standalone version where we can make our own trinkets?

**Comment by FaultyFunctions** [comment]
Oh I just saw that Blank Slate exists. Would it be best to just download ValhallaMMO with Blank Slate and Valhalla Trinkets if I want to make my own custom trinkets? Nothing is changed with vanilla unless I want it changed this way, right?

**Comment by Athlaeos** [comment]
Yup, pretty much. Though I would advise you enable the custom damage system in config.yml anyway, as there's currently a bug that voids immunity frames because of its disabling

**Comment by Athlaeos** [comment]
Also no, no update. It's not on my radar right now as I have other more ambitious projects going on that take my priority

**Comment by FaultyFunctions** [comment]
> Yup, pretty much. Though I would advise you enable the custom damage system in config.yml anyway, as there's currently a bug that voids immunity frames because of its disabling

Awesome thanks! What's the difference between the custom damage system and vanilla? Is it just vanilla until you tack stuff on or do vanilla items get different damage calculations?

**Comment by Athlaeos** [comment]
its a different damage calculation yeah. was required to make the plugin work with armor values of above 20. you might want to tweak it a bit, like changing the 15 to a 5, it'll make armor more closely resemble vanilla strength
